name: Generate and Deploy Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate_snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake.svg
          template: default
          base: light

  deploy_snake:
    runs-on: ubuntu-latest

    needs: generate_snake

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
